version: '3.8'

services:
  app:
    image: blog_be:1.0.0
    container_name: blog-panel-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - minio
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/blog_panel
      - JWT_SECRET=your_super_secret_key_change_in_production
      - JWT_EXPIRE=24h
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=blog-media
      - MINIO_PUBLIC_URL=http://localhost:9000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - blog-network

  mongodb:
    image: mongo:latest
    container_name: blog-panel-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog-network

  minio:
    image: minio/minio:latest
    container_name: blog-panel-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongodb_data:
  minio_data: 